stages:
  - test
  - coverage

test:
 stage: test
 tags:
   - features-amd64
 script:
   - echo "Build and test docker image"
   - docker build --no-cache -t libmpc .
   - docker run --cap-add SYS_PTRACE --rm libmpc

coverage:
 stage: coverage
 tags:
   - features-amd64
 script:
   - echo "Generate coverage figures"
   - docker run --rm libmpc ./scripts/coverage.sh
 coverage: '/lines......: (\d+.\d+%)/'

