language: c
compiler: gcc
sudo: true
dist: trusty

addons:
  sonarcloud:
    organization: "qredo-github"
    token:
      secure: "CSY+DkwVu9M2zlOLU51aW92bKK7T5y725tJM3h3yHp3YcQpMYSL8ZBYYQTKjP3laanjivJQgq8gilvUPuZTXCv7YaakSiymxdFhJYzXIPhiv17hgmqBZdDI6t0+Vs5MvGqlXK/hu6y/SjRydx/xSi2TNA5HZ8OxEgfsyJU+CHQPo25+bL3xrGCAGFCAQ7NeXFKFffwOvcP4rX6crSzNkB84LvKAPfo5+QAz8HREbZ1KqSFOVJw28LWWZNsRLAa+BY7TZR4BwZlFZGHQ1Z1LLAgj4Q5GK8eFeAEj+/sK0mLzAOsMk3sbAfbPzXVINuxNK8M5vD63OgUHG/eU9EtturIyMB5L50Qh8BB3U31n3RsEpt0t3IfPIShYcd0kKLSmdBbNNRDlcSNOErR+zn0184muXNkgw9qMmgCds6keMuyQyPBUd7lxJ4sw26fRlVTdw/FWEUrbolJ7U+StGtV63Sd/w0kqBva1+H1hNwnwL9D8AgNK0T0xx5xR8Qh9/bwCRwrKRhFcjV+lu9UCNDmbJgLs3fjpGd0STpJMCoGQYEFGJvxMPSHei9EFvMy8YLrYMIyCVXjRLHXzmj7o3vvGu0TinnnLv2OJWYdxbzFUzTsHZOT4lKhHiQ+2dLLl6iyQRY8iuLbXkVIYqDWYdIM8XWOl6OCK9QVaOZGBsCFqVjaA="

install:
  - gem install coveralls-lcov

services:
- docker

jobs:
  include:
  - stage: sonar
    script:
    - echo "Run static code analysis"
    - git clone https://github.com/apache/incubator-milagro-crypto-c.git -b issue51
    - cd incubator-milagro-crypto-c
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=ON -D AMCL_CHUNK=64 -D AMCL_CURVE="" -D AMCL_RSA="2048,4096,8192" -D BUILD_PYTHON=OFF -D BUILD_BLS=OFF -D BUILD_WCC=OFF -D BUILD_MPIN=OFF -D BUILD_X509=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..
    - make
    - make test
    - sudo make install
    - cd ../..
    - rm -rf python
    - mkdir build
    - cd build
    - cmake -D BUILD_TESTS=OFF -D BUILD_EXAMPLES=OFF -D BUILD_BENCHMARK=OFF ..
    - build-wrapper-linux-x86-64 --out-dir bw-output make
    - mv bw-output ..
    - cd ..
    - rm -rf test
    - rm -rf examples
    - rm -rf benchmark    
    - sonar-scanner -X
  - stage: test
    script:
    - echo "Build docker image and run tests"
    - docker build -t libmpc .
    - docker run --cap-add SYS_PTRACE --rm libmpc 
  - stage: coverage
    script:
    - echo "Generate coverage figures"
    - docker build -t libmpc .
    - CONTAINER_ID=$(docker run --cap-add SYS_PTRACE -d libmpc ./scripts/coverage.sh)
    - sleep 100
    - docker logs $CONTAINER_ID
    - docker cp ${CONTAINER_ID}:"/root/target/Coverage/coverage" ./
    - docker rm -f ${CONTAINER_ID} || true
    - sed -i "s|root|home/travis/build/qredo/libmpc|" ./coverage/libmpc.info
    - coveralls-lcov /home/travis/build/qredo/libmpc/coverage/libmpc.info

cache:
  directories:
    - '$HOME/.sonar/cache'




